using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CoreBB.Web.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CoreBB.Web.Controllers
{
    public class UserController : Controller
    {
        [Authorize]
        [AllowAnonymous, HttpGet]
        public async Task<IActionResult> Register()
        {
            //  await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [AllowAnonymous, HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("registro inválido");
            }
            model.Name = model.Name.Trim();
            model.Password = model.Password.Trim();
            model.RepeatPassword = model.RepeatPassword.Trim();
            var targetUser = _dbContext.User.SingleOrDefault(u => u.Name.Equals(model.Name, StringComparison.CurrentCulture));
            if(targetUser != null)
            {
                throw new Exception("Usuario já existe");

            }
            if (!model.Password.Equals(model.RepeatPassword))
            {
                throw new Exception("Passwords diferentes");
            }
            var hasher = new PasswordHasher<User>();
            //adds the constraint that the username in the database must be unique.
            targetUser = new User { Name = model.Name, RegisterDateTime = DateTime.Now, Description = model.Description };
            targetUser.PasswordHash = hasher.HashPassword(targetUser, model.Password);

            //In the HTTP POST Register action, we validate the view model instance 
            //(which is generated by the ASP.NET Core model binding system from the form data), 
            //then create a user from the valid view model and save the user to the database. When creating the user, the code:
            if (_dbContext.User.Count() == 0)
            {
                targetUser.IsAdministrator = true;
            }
            await _dbContext.User.AddAsync(targetUser);
            await _dbContext.SaveChangesAsync();
            await LogInUserAsync(targetUser);

            return RedirectToAction("Index", "Forum");
        }

        private async Task LogInUserAsync(User user)
        {
            var claims = new List<Claim>();
            claims.Add(new Claim(ClaimTypes.Name, user.Name));
            if (user.IsAdministrator)
            {
                claims.Add(new Claim(ClaimTypes.Role, Roles.Administrator));
            }
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);
            user.LastLogInDateTime = DateTime.Now;
            await _dbContext.SaveChangesAsync();
        }

        [AllowAnonymous, HttpGet]
        public async Task<IActionResult> LogIn()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [AllowAnonymous, HttpPost]
        public async Task<IActionResult> LogIn(LogInViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Usuário Inválido");
            }
            var targetUser = _dbContext.User.SingleOrDefault(u => u.Name.Equals(model.Name, StringComparison.CurrentCultureIgnoreCase));
            if (targetUser == null)
            {
                throw new Exception("Usuário não existe");
            }
            var hasher = new PasswordHasher<User>();
            var result = hasher.VerifyHashedPassword(targetUser, targetUser.PasswordHash, model.Password);
            if (result != PasswordVerificationResult.Success)
            {
                throw new Exception("Password está errado");
            }

            await LogInUserAsync(targetUser);
            return RedirectToAction("Index", "Home");

        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public IActionResult Detail(string name)
        {
            var user = _dbContext.User.SingleOrDefault(u => u.Name == name);
            if (user == null)
            {
                throw new Exception($"Usuario '{name}' NON EXCISTEEE");
            }

            return View(user);
        }

        [HttpGet]
        public IActionResult Edit(string name)
        {
            if(User.Identity.Name != name && !User.IsInRole(Roles.Administrator))
            {
                throw new Exception("Operação NEGADA");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == name);
            if(user == null)
            {
                throw new Exception($"Usuario '{name}' NON EXCISTEEE");
            }
            var model = UserEditViewModel.FromUser(user);
            return View(model);
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Index()
        {
            var users = _dbContext.User.ToList();
            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid user information.");
            }

            var user = _dbContext.User
                .SingleOrDefault(u => u.Name.Equals(model.Name, StringComparison.CurrentCultureIgnoreCase));

            if (user == null)
            {
                throw new Exception("User does not exist.");
            }

            if (!string.IsNullOrEmpty(model.Password))
            {
                model.Password = model.Password.Trim();
                model.RepeatPassword = model.RepeatPassword.Trim();
                if (!model.Password.Equals(model.RepeatPassword))
                {
                    throw new Exception("Passwords are not identical.");
                }

                var hasher = new PasswordHasher<User>();
                if (!User.IsInRole(Roles.Administrator))
                {
                    var vr = hasher.VerifyHashedPassword(user, user.PasswordHash, model.CurrentPassword);
                    if (vr != PasswordVerificationResult.Success)
                    {
                        throw new Exception("Please provide correct current password.");
                    }
                }

                user.PasswordHash = hasher.HashPassword(user, model.Password);
            }

            user.Description = model.Description;

            if (User.IsInRole(Roles.Administrator))
            {
                user.IsAdministrator = model.IsAdministrator;
                user.IsLocked = model.IsLocked;
            }

            _dbContext.User.Update(user);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Detail", new { name = user.Name });
        }



        private CoreBBContext _dbContext;

        public UserController(CoreBBContext dbContext)
        {
            _dbContext = dbContext;
        }

    }
}